### ISSUE TITLE
有没有详细的配置说明

### ISSUE THREAD

**Issue by rilweic** [anerg2046/Caddy_V2ray#1]
本地用的clash客户端，有相关配置说明吗

**Comment by anerg2046** [comment]
`docker logs caddy_v2ray`
可以看到vmess://ewogICAgInYiOiAiMiIsCiAgICAicHMiOiAidjIubW9vaW0uY29tIiwKICAgICJhZGQiOiA... 这样一长串，复制下来导入即可
