### ISSUE TITLE
提供的配置模板又有问题

### ISSUE THREAD

**Issue by 362227** [anerg2046/Caddy_V2ray#2]
![QQ截图20220918091951](https://user-images.githubusercontent.com/91358231/190881503-d4c29124-d196-450a-b902-e511b310b721.jpg)
各种报错，格式有问题

**Comment by anerg2046** [comment]
大概率是你没有名为“work-net”的网络，这只是我自己用的，你需要改成你的，或者如果你只用默认网络的话，删掉所有"work-net"相关的内容
