### ISSUE TITLE
新增arm机器支持

### ISSUE THREAD

**Issue by zhuxindong** [anerg2046/Caddy_V2ray#6]
能否新增arm机器支持

**Comment by anerg2046** [comment]
好，稍后我改改。不过一般vps很少有arm的吧

**Comment by zhuxindong** [comment]
oracle很多的arm机，我自己也fork改了一份，实测已经可用了，只需要改一下dockerfile里v2flay的版本就行
https://github.com/zhuxindong/Caddy_V2ray_ARM64

**Comment by zhuxindong** [comment]
https://github.com/anerg2046/Caddy_V2ray/compare/main...zhuxindong:Caddy_V2ray_ARM64:main
